### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by floogulinc** [frc2879/2016-knight-fury#1]
## Commands
- [x] Move to relative location (using encoders, and possibly the IMU)
- [ ] Move arm to position (using potentiometer)
  - [ ] Move arm to shooting position (and tie into shoot ball command)
  - [ ] Move arm up all the way
## Sensors
- [x] Add encoder stuff to drivetrain
- [ ] Add potentiometer to arm
- [x] Add limit switches to arn
